# aqui tenho que colocar o nome do pipeline (fluxo de trabalho - workflow)
name: Primeiro Workflow
# em quais eventos de gatilho eu quero que dispare meu script
on:
  push:
    branches:
      -developer
      -main
      -master
  pull_request:
    branches: [main, master]
# quais são os (fluxos) a serem executados pelo workflow    

jobs:
  Primeiro-fluxo:
    
    # este é o nome do fluxo de trabalho
      name: Job 1
      # para ser executado nesta máquina virtual (container linux)
      runs-on: ubuntu-latest 
      # agora irei incluir os passsos do script
      steps:
        - name: Passo 1
          run: echo "Executando o primeiro passo"
        - name: Passo 2
          run: echo"Executando o segundo passo"
        - name: Passo3
          run:  echo "Executando o terceiro passo"

          Segundo-fluxo:
    
    # este é o nome do fluxo de trabalho
      name: Job 2
      # para ser executado nesta máquina virtual (container linux)
      runs-on: ubuntu-latest 
      # agora irei incluir os passsos do script
      steps:
        - name: Passo 3
          run: echo "Executando o terceiro passo"
        - name: Passo 4
          run: echo"Executando o quarto passo"
        - name: Passo 5
          run:  echo "Executando o quinto passo"

          Terceiro-fluxo:
    
    # este é o nome do fluxo de trabalho
      name: Job 3
      # para ser executado nesta máquina virtual (container linux)
      runs-on: ubuntu-latest 
      # agora irei incluir os passsos do script
      steps:
        - name: Passo 6
          run: echo "Executando o sexto passo"
        - name: Passo 7
          run: echo"Executando o sétimo passo"
        - name: Passo 8
          run:  echo "Executando o oitavo passo"
